name: Run Docker Image

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository_owner }}/sweety_corner:latest

      - name: Run container
        run: docker run --rm -e RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} -p 80:80 ghcr.io/${{ github.repository_owner }}/sweety_corner:latest